### PR TITLE
Replace old folder browser with better, not Windows 95 era one...

### PR DESCRIPTION
**Pull request by sjennison**
Replaces with new UI folder browser

### CODE REVIEW

**Review by CSX8600 — APPROVED** [review]
These changes look good - would you want to make a similar update to the folder browser in Update project as well?  If not, I will go ahead and commit this.

**Comment by sjennison** [comment]
Yeah I can add that - should I make a new PR with that and close this one?

**Comment by CSX8600** [comment]
You can just make it a part of this PR tbh

**Comment by sjennison** [comment]
👍

**Comment by RavenholmZombie** [comment]
Bread 👍

**Pull request merged**
