### PR TITLE
CS-sided AR Invoicing

### PR DESCRIPTION
**Pull request by CSX8600**
Be warned - I haven't done a self-review on this so there might be some shitty stuff in here.

### CODE REVIEW

**Comment by RavenholmZombie** [comment]
Do a self-review first lol

**Comment by CSX8600** [comment]
> Do a self-review first lol

done

**Comment by RavenholmZombie** [comment]
> done

We'll see about that

**Comment by CSX8600** [comment]
Closing to reset Viewed files

**Pull request closed without merging**
